#!/bin/sh /etc/rc.common
# (C) 2013 openwrt.org

START=40

start() {                            
	echo "this file has been obseleted. please call \"/sbin/block mount\" directly"
	/sbin/block mount
	[ -f /media/sysupgrade.tgz ] && {
		echo "- config restore -"
		cd /
		tar xzf /media/sysupgrade.tgz
	}
}

stop() {                            
	echo "this file has been obseleted. please call \"/sbin/block umount\" directly"
	/sbin/block umount
}
